# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f16d9083263de89a6288539968e97a218a3137a039a81d49fb4f4a201aa14e18fb6b956e918b971d552cc9a862f81063bf7431ad150c567ac1fcb8a9a01fcdca

test:
  secret_key_base: 039c9be2c6fe15c72a0e99ceb484077384c7769e39fae2fc6097ccbb1d65885651b359dfa97c9a87ff2593febe97b5abc3224c5c6e82d1643a7c124d6dff982a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
